### PR TITLE
Allow overriding http.Client

### PR DESCRIPTION
**Pull request by AnalogJ**
adding HttpClient public property to Client, so that it can be overridden with Proxy support, custom headers/useragent & GoVCR for testing & http request playback

https://github.com/seborama/govcr

### CODE REVIEW

**Comment by AnalogJ** [comment]
Anything I can do to help get this merged?

**Comment by izgeri** [comment]
@AnalogJ can you give more context for why this change is needed? As you can see, the members of the `Client` struct are all unexported at current. How are you using this library that you need the functionality you referenced?
> it can be overridden with Proxy support, custom headers/useragent & GoVCR for testing & http request playback

In particular, I am wondering if there may be another way to achieve what you need without making the `httpClient` exportable.

**Comment by AnalogJ** [comment]
Basically I'm using a library called go-vcr to record all my Http request/response interactions with the server and play them back during tests. 

To do this, the `http.Client` used by the conjur api library needs replaced with a go-vcr modified version (that still conforms to the http.Client interface).

Here's and example of my code to generate a govcr modified http.Client (in a different project):
https://github.com/AnalogJ/capsulecd/blob/master/pkg/scm/scm_bitbucket_test.go#L25-L56

and here's an example of the Http request/response recording:
https://github.com/AnalogJ/capsulecd/blob/master/pkg/scm/testdata/govcr-fixtures/TestScmGithub_RetrievePayload_PullRequest.cassette#L109

Thats my specific usecase, but another reason to make the `http.Client` public is that users of the library would then be able to customize the http transport used, and define proxies which are used heavily in corporate environments.

**Comment by izgeri** [comment]
@AnalogJ thanks for the additional context. I'd prefer to have `Get` / `Set` methods added for the `httpClient` member of the `Client` struct, if we are going to add something (rather than making `httpClient` exportable).

Paging @dustinmm80 and @apotterri to get their feedback as well - I recently had a similar request for this repo, and. they had opinions :)

**Comment by izgeri** [comment]
Also @AnalogJ have you signed a contributor agreement? If not, you can find out more info [here](https://github.com/cyberark/conjur/blob/master/CONTRIBUTING.md) - please let me know if you have any questions / problems :)

**Pull request merged**
