### PR TITLE
Add support for authn-jwt with JWT token

### PR DESCRIPTION
**Pull request by infamousjoeg**
### Desired Outcome

The desired outcome of this PR is to add support for authenticating using authn-jwt through the conjur-api-go SDK where the token is provided as a raw value rather than being located in a file at a particular path that can be read.

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

- _What's changed? Why were these changes made?_
This PR adds a new environment variable called `CONJUR_AUTHN_JWT_TOKEN` that, when present, overrides the requirement to provide `CONJUR_TOKEN_PATH`.  If the `CONJUR_AUTHN_JWT_TOKEN` is not present, `CONJUR_TOKEN_PATH` is assumed and the typical logic established prior to this PR still applies.
- _How should the reviewer approach this PR, especially if manual tests are required?_
I have a GitLab self-hosted instance that is using this in order to authenticate with the GitLab CI generated JWT at runtime to retrieve secrets needed in the pipeline. I am happy to have a session where the reviewer can see this working in action where a test environment supporting an authn-jwt process is not available.
- _Are there relevant screenshots you can add to the PR description?_
The authn-jwt for GitLab project is located at https://github.com/infamousjoeg/authn-jwt-gitlab.  Here is the successful usage of the Go binary created and built into a Docker container in a GitLab CI pipeline utilizing the CI job's generated JWT for authentication to Conjur:
.gitlab-ci.yml
image
Output
image
(Don't worry, that password has since been rotated.)

### Connected Issue/Story

Resolves # n/a

CyberArk internal issue ID: n/a

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [x] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [x] There are no security aspects to these changes

### CODE REVIEW

**Comment by szh** [comment]
Hey @infamousjoeg,

@doodlesbykumbi plans to take a look at this. In the meantime, it looks like the build is failing.

**Comment by infamousjoeg** [comment]
> Hey @infamousjoeg,
> 
> @doodlesbykumbi plans to take a look at this. In the meantime, it looks like the build is failing.

I am not on the VPN to check Jenkins -- can you share why it is failing with me?

**Comment by infamousjoeg** [comment]
@szh @doodlesbykumbi The failure is now in your court. My code passes and it fails on a step involving Summon fetching secrets for some reason.

**Comment by doodlesbykumbi** [comment]
@infamousjoeg Just wanted to let you know that I'm intending to review this tomorrow (Tuesday).

**Comment by infamousjoeg** [comment]
Any updates on this? @doodlesbykumbi

**Comment by szh** [comment]
@infamousjoeg I made some fixes and cleaned some stuff up and squashed all the commits. Is it OK with you if I merge this after the CI passes?

**Comment by infamousjoeg** [comment]
@szh SHIP IT! :rocket:

**Review by szh — APPROVED** [review]
LGTM!

**Pull request merged**
